name: Deploy CreatorCatalyst-PostsProcessing

on:
  push:
    paths:
      - 'CreatorCatalyst-PostsProcessing/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd CreatorCatalyst-PostsProcessing
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .

    - name: Package and deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'
      run: |
        cd CreatorCatalyst-PostsProcessing
        zip -r9 ../cc-postsprocessing.zip .
        aws lambda update-function-code --function-name CreatorCatalyst-PostsProcessing --zip-file fileb://../cc-postsprocessing.zip
