name: Test Secrets

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: ''
      aws_region:
        description: 'AWS Region for deployment'
        required: false
        default: 'us-west-1'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment || 'default' }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ github.event.inputs.aws_region || 'us-west-1' }}" >> $GITHUB_ENV

      - name: Check environment variable
        run: |
          echo "Environment is: $ENVIRONMENT"
          
      - name: Debug secrets
        run: |
          echo "AWS_ACCESS_KEY_ID is set to: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY is set to: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION is set to: ${{ secrets.AWS_REGION }}"
