name: Test Secrets

on:
  push:
    branches:
      - develop

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          echo "AWS_ACCESS_KEY_ID is set to: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY is set to: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION is set to: ${{ secrets.AWS_REGION }}"
